### ISSUE TITLE
No need to install libpcap-dev on macOS

### ISSUE THREAD

**Issue by idoco** [colinnewell/pcap2har-go#1]
Tested on macOS Catalina 10.15.7 and it worked without installing libpcap-dev. It might be worth mentioning that on the readme file.

Thank you for this awesome project.

**Comment by colinnewell** [comment]
Thanks for the report.  I knew the instruction wasn't quite right for Mac's, but I hadn't realised they would have it out of the box.  That's pretty neat!

I've created PR #2 to address this.  I've created it as a pull request so you can comment on it.  I'll probably merge it tomorrow.
